### ISSUE TITLE
[Bug] Pages doesn't work

### ISSUE THREAD

**Issue by kapitanpatatas** [0zyxel0/tapper_dev#6]
Some pages return this error
![error](https://user-images.githubusercontent.com/2719961/63139841-520c6880-c012-11e9-8621-7fac6cd4aa2f.PNG)

Pages found affected
Gate
Change Logo
Change Header

**Comment by 0zyxel0** [comment]
[Notes] DB was not running the updated version without the background_table and header_settings table.
